name: Deploy Portfolio to S3

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Sync to S3
      uses: aws-actions/s3-sync@v2
      with:
        bucket: ${{ secrets.S3_BUCKET_NAME }}
        region: ${{ secrets.AWS_REGION }}
        delete: true  # deletes files not in repo from S3
        no-guess-mime-type: true
        content-type: text/html
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

